// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActorController from "./actor_controller"
application.register("actor", ActorController)

import ActorPhotosController from "./actor_photos_controller"
application.register("actor-photos", ActorPhotosController)

import ArticlesController from "./articles_controller"
application.register("articles", ArticlesController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import OrderPhotosController from "./order_photos_controller"
application.register("order-photos", OrderPhotosController)

import VideoHeightController from "./video_height_controller"
application.register("video-height", VideoHeightController)

import VideosController from "./videos_controller"
application.register("videos", VideosController)
