// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActorController from "./actor_controller"
application.register("actor", ActorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import VideoHeightController from "./video_height_controller"
application.register("video-height", VideoHeightController)
