meta_name: "Carrelo Squad"
meta_title: "Carrelo Squad - Actors Management"
meta_description: "Carrelo Squad is a portuguese actors management platform."
meta_image: "" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards